# OS
- ubuntu
- Intel i9 10900
- NVIDIA GeForce RTX 3080
- Memory 64GB

## Import

In [2]:
import pandas as pd
import numpy as np

## Load Result data

In [12]:
# RandomForest
model_rf = pd.read_csv("../OUT/RFResult.csv")

# XGBoost
model_xgb = pd.read_csv("../OUT/XGBResult.csv")

#ExtraTree
model_xtr = pd.read_csv("../OUT/ExtraTreeResult.csv")

# LSTM
model_lstm = pd.read_csv("../OUT/LSTMResult.csv")

In [26]:
model_rf

,ID,2023-04-05,2023-04-06,2023-04-07,2023-04-08,2023-04-09,2023-04-10,2023-04-11,2023-04-12,2023-04-13,...,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24,2023-04-25
0,0,0.641,1.019,1.632,4.054,3.898,4.548,5.951,5.659,5.029,...,4.035,4.072,5.470,4.219,3.191,4.005,2.752,3.225,3.862,3.824
1,1,0.339,0.664,0.984,0.680,0.726,0.770,0.781,0.850,1.001,...,0.843,0.846,0.831,0.904,0.906,0.939,0.825,0.796,0.869,1.039
2,2,0.192,0.018,0.044,0.066,0.026,0.026,0.031,0.031,0.031,...,0.027,0.046,0.050,0.050,0.050,0.049,0.047,0.042,0.041,0.045
3,3,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,4,0.554,1.311,4.017,5.119,4.235,6.392,5.405,7.635,4.788,...,5.711,4.860,4.890,4.873,4.346,5.518,5.066,5.339,4.061,5.842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,6.565,12.747,15.676,16.933,16.469,13.657,15.258,27.584,26.979,...,46.576,36.481,25.387,31.535,42.164,40.339,28.072,19.795,17.873,17.199
15886,15886,13.031,32.600,38.529,39.356,39.073,32.304,25.149,18.337,16.969,...,15.324,14.147,13.477,19.617,31.137,39.508,39.816,40.291,40.494,34.662
15887,15887,0.237,0.115,0.112,0.087,0.163,0.152,0.052,0.018,0.008,...,0.053,0.004,0.083,0.034,0.092,0.009,0.027,0.039,0.031,0.028
15888,15888,1.951,1.783,1.797,1.727,1.674,1.424,1.319,1.305,0.998,...,0.793,0.947,0.866,1.007,1.046,1.064,0.990,0.977,1.170,1.147
15889,15889,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [17]:
model_xgb

,ID,2023-04-05,2023-04-06,2023-04-07,2023-04-08,2023-04-09,2023-04-10,2023-04-11,2023-04-12,2023-04-13,...,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24,2023-04-25
0,0,1.875707e-02,-1.061693e-03,1.382190e-01,1.502127e-01,1.861454e-01,-2.192439e-02,-3.582488e-02,-8.227029e-03,-2.903079e-02,...,-3.449471e-02,6.052077e-03,7.966681e-02,1.013089e-01,-4.642380e-02,1.873930e-01,-6.082181e-02,-4.892444e-02,-1.080223e-02,1.524917e-01
1,1,5.803353e-01,1.780764e+00,1.883223e+00,1.463577e+00,8.349496e-01,1.073595e+00,6.835589e-01,9.532107e-01,1.327120e+00,...,1.886086e+00,1.936385e+00,1.843345e+00,2.031437e+00,2.043390e+00,1.944383e+00,1.478568e+00,8.068211e-01,1.037001e+00,1.127634e+00
2,2,6.334311e-01,1.187673e+00,8.345875e-01,1.250918e+00,9.286813e-01,9.034623e-01,1.421519e+00,1.375549e+00,1.377469e+00,...,2.393561e+00,2.267711e+00,2.503266e+00,3.303199e+00,3.127393e+00,2.606464e+00,3.017428e+00,2.895465e+00,2.828007e+00,2.257701e+00
3,3,1.013373e-03,-4.272409e-04,-9.489714e-04,-9.489714e-04,4.256329e-04,-4.851846e-04,4.256165e-04,1.616589e-03,1.759748e-04,...,4.256329e-04,-5.466407e-04,3.641605e-04,-1.193554e-03,1.309866e-03,-1.256799e-04,-1.256799e-04,-1.066001e-04,-1.017416e-03,-7.611254e-04
4,4,1.815153e+00,1.439855e+00,6.432405e+00,2.813748e+00,1.497199e+01,6.998054e+00,9.128499e+00,1.501894e+01,5.397395e+00,...,4.349985e+00,6.401145e+00,4.333243e+00,3.991835e+00,3.803484e+00,3.761543e+00,3.770421e+00,3.532610e+00,2.656067e+00,4.580103e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,7.216310e+00,2.058504e+01,4.086350e+01,4.721569e+01,5.366553e+01,8.926433e+00,7.874939e+00,5.669542e+01,3.724804e+01,...,2.069405e+01,2.505710e+01,1.495894e+01,2.278324e+01,7.242497e+00,1.067965e+01,1.239032e+01,1.423946e+01,1.289237e+01,1.404441e+01
15886,15886,2.171164e+01,3.119193e+01,2.824169e+01,3.359487e+01,2.896367e+01,2.439463e+01,1.425198e+01,1.493124e+01,1.062793e+01,...,6.298236e+00,4.331406e+00,4.863157e+00,2.018025e+01,2.835241e+01,3.212318e+01,3.214997e+01,3.311542e+01,2.846579e+01,9.611325e+00
15887,15887,9.744983e-02,-1.978524e-02,4.582837e-01,3.084876e-01,5.212125e-02,4.364941e-02,-4.591609e-02,-7.979386e-02,5.448635e-03,...,1.355985e-01,-4.594597e-03,5.398894e-05,-1.132026e-01,3.463393e-01,1.134635e-02,2.029026e-02,-1.587147e-02,7.804985e-02,-4.265662e-02
15888,15888,2.222587e+00,1.761461e+00,1.928541e+00,1.879419e+00,1.570451e+00,1.707083e+00,1.737450e+00,2.061563e+00,2.055917e+00,...,9.589480e-01,1.595667e+00,1.716552e+00,2.141819e+00,1.826517e+00,1.847581e+00,1.790882e+00,1.827801e+00,1.214826e+00,1.196480e+00
15889,15889,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,...,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45,1.401298e-45

In [28]:
model_xtr

,ID,2023-04-05,2023-04-06,2023-04-07,2023-04-08,2023-04-09,2023-04-10,2023-04-11,2023-04-12,2023-04-13,...,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24,2023-04-25
0,0,0.775,2.275,4.560,4.660,3.890,4.885,5.495,6.560,5.605,...,4.060,4.570,5.370,4.455,3.955,4.160,3.520,3.965,4.030,3.880
1,1,0.805,1.300,1.100,0.715,0.495,0.550,0.675,0.690,0.705,...,0.665,0.685,0.740,0.815,0.790,0.820,0.810,0.635,0.760,0.930
2,2,0.050,0.085,0.145,0.230,0.280,0.345,0.485,0.720,1.010,...,1.970,2.250,2.255,2.265,2.230,2.245,2.575,2.565,2.545,2.435
3,3,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,4,0.960,3.070,5.270,5.600,3.670,6.930,5.155,6.225,5.480,...,5.790,5.400,4.985,4.150,4.185,5.280,4.610,5.375,4.615,5.265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,3.505,12.480,19.680,21.125,20.060,14.370,10.595,14.580,22.990,...,51.680,48.065,25.165,16.745,21.825,24.495,26.555,23.090,20.030,18.800
15886,15886,8.020,11.995,13.960,16.085,15.830,16.590,12.735,12.075,12.805,...,14.010,12.220,11.425,10.220,10.330,10.150,9.245,9.055,8.100,9.825
15887,15887,0.050,0.085,0.100,0.065,0.135,0.210,0.135,0.075,0.040,...,0.135,0.020,0.115,0.110,0.205,0.045,0.055,0.120,0.135,0.030
15888,15888,2.055,1.420,1.395,1.365,1.365,1.490,1.430,1.650,1.665,...,1.185,1.350,1.140,1.135,1.135,1.090,0.985,1.010,1.530,1.585
15889,15889,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [29]:
model_lstm

,ID,2023-04-05,2023-04-06,2023-04-07,2023-04-08,2023-04-09,2023-04-10,2023-04-11,2023-04-12,2023-04-13,...,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24,2023-04-25
0,0,8.351367,6.327543,4.560046,3.959054,4.025747,4.229504,4.417250,4.210002,3.789438,...,3.458292,3.738157,3.932794,3.783056,3.353543,3.101188,2.967621,3.183917,3.540329,3.690207
1,1,0.882580,1.102566,1.193146,1.073286,0.936101,0.920137,1.053580,1.224930,1.332253,...,1.013678,0.992339,1.106031,1.273732,1.384576,1.354384,1.199889,1.067575,1.056338,1.159638
2,2,1.938442,2.109203,1.956542,1.702376,1.731948,2.106312,2.612339,2.854327,2.741652,...,2.109143,2.460108,2.913439,3.134696,3.018106,2.637640,2.361684,2.414484,2.809238,3.268814
3,3,1.917677,1.775509,2.128999,2.738870,3.505056,3.969312,3.955992,3.325567,2.803377,...,4.293756,4.639123,4.486425,3.841604,3.359124,3.421237,4.022167,4.946761,5.427677,5.195076
4,4,4.508450,4.903590,5.018604,4.708110,4.147428,3.779014,3.867056,4.286287,4.778788,...,4.216067,3.849067,3.928320,4.367663,4.896182,5.085810,4.780595,4.261641,3.926303,3.950658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,10.102321,12.752632,14.483916,13.696866,12.382846,11.872946,12.859807,14.485940,15.806660,...,13.475904,12.795017,13.701035,15.282044,16.742228,17.056488,15.527987,14.195243,13.677622,14.114490
15886,15886,6.798822,9.222642,10.687661,10.143623,8.969073,7.992620,8.391903,9.510892,10.841561,...,9.557906,8.432074,8.775166,9.868463,11.316847,12.131147,11.199536,10.002648,9.241451,9.046654
15887,15887,1.224737,1.172174,0.929043,0.720862,0.717533,0.923393,1.226600,1.362587,1.288003,...,0.920948,1.110280,1.386655,1.512206,1.442830,1.236145,1.077651,1.115426,1.345948,1.602346
15888,15888,1.682928,1.445865,1.376361,1.458956,1.680055,1.886943,1.921884,1.761384,1.561183,...,1.759224,1.950364,1.987468,1.827703,1.622493,1.526051,1.597082,1.812490,2.009659,2.040134
15889,15889,0.964354,0.729915,0.436362,0.344063,0.355119,0.384027,0.409818,0.410247,0.384521,...,0.360892,0.391348,0.421595,0.434002,0.385104,0.365827,0.351479,0.391966,0.443282,0.481032

## ensemble!

In [18]:
model_ensemble = model_rf + model_xgb + model_xtr+model_lstm
model_ensemble = model_ensemble/4
model_ensemble = np.round(model_ensemble,0).astype(int)

In [19]:
modify = model_ensemble.iloc[:, 1:]
modify[modify<1] = 1 # 최저 판매량 값으로 대치
model_ensemble.iloc[:,1:] = modify

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:3093: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._where(-key, value, inplace=True)

In [20]:
model_ensemble

,ID,2023-04-05,2023-04-06,2023-04-07,2023-04-08,2023-04-09,2023-04-10,2023-04-11,2023-04-12,2023-04-13,...,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24,2023-04-25
0,0,2,2,3,3,3,3,4,4,4,...,3,3,4,3,3,3,2,3,3,3
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,2,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2
3,3,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,4,2,3,5,5,7,6,6,8,5,...,5,5,5,4,4,5,5,5,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15885,15885,7,15,23,25,26,12,12,28,26,...,33,31,20,22,22,23,21,18,16,16
15886,15886,12,21,23,25,23,20,15,14,13,...,11,10,10,15,20,23,23,23,22,16
15887,15887,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
15888,15888,2,2,2,2,2,2,2,2,2,...,1,1,1,2,1,1,1,1,1,1
15889,15889,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

## Save

In [33]:
model_ensemble.to_csv('../OUT/Please.csv', index=False)